spring:
  datasource:
    druid:
      url: jdbc:sqlserver://xxx.xxx.xxx.xxx:1433;databaseName=test
      username: sa
      password: 'sa'
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      initial-size: 5
      max-active: 300
      max-wait: 60000
      validation-query: select 'x'
      validation-query-timeout: 3000
      filters: slf4j
      db-type: sqlserver
      filter:
        commons-log:
          statement-executable-sql-log-enable: true
          result-set-log-enabled: true